---
mysql_root_password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits,punctuation') }}"

# Databases.
mysql_databases:
   - name: example
     collation: utf8_general_ci
     encoding: utf8

# Users.
mysql_users:
   - name: example
     host: 127.0.0.1
     password: secret
     priv: "*.*:USAGE"
