---
# Databases.
mysql_databases:
   - name: example
     collation: utf8_general_ci
     encoding: utf8

# Users.
mysql_users:
   - name: example
     host: 127.0.0.1
     password: secret
     priv: "*.*:USAGE"
