---
php_packages:
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-gd
  - php-imap
  - php-ldap
  - php-mbstring
  - php-opcache
  - php-pdo
  - php-pear
  - php-xml
  - php-xmlrpc
  - php-mcrypt
  - php-snmp
  - php-process