---
- name: mysql rpm install
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm

- name: mysql install
  yum: name=mysql-community-server state=installed

- name: MySQL-python install
  yum: name=MySQL-python state=installed

- name: Copy configuration
  template: src=my.cnf.j2 dest=/etc/my.cnf backup=yes
  notify: mysqld restart

- name: mysqld running and enabled
  service:
    name=mysqld
    state=started
    enabled=yes
  tags: mysqld
  sudo: yes

- name: first root password
  shell: cat /var/log/mysqld.log | grep password | awk '{ print $NF }' | head -n 1
  register: mysql_passwd

- name: check mysql root password
  command: mysqlshow -uroot -p'{{ mysql_passwd.stdout }}'
  register: root_check
  ignore_errors: True

- name: set mysql root password
  command: mysql --connect-expired-password -uroot -p'{{ mysql_passwd.stdout }}' -e "set password for root@'localhost' = PASSWORD('{{ mysql_root_passwd }}')"
  when: root_check.stderr.find('denied') == -1