---
- name: "sshuser | Create ansible user"
  user:
    name: "{{ ansible-user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present

- name: sshuser | Set authorized key for ansible user copying it from current user
  authorized_key:
    user: ansible-user
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"