---
- name: common | Set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: common | Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: common | Add epel-release
  yum:
    name: epel-release
    state: present

- name: common | Add repository 'remi-repo'
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    state: present

- name: common | Install base
  yum: name={{ item }} state=present
  with_items:
    - wget
    - vim
    - gcc
    - libxml2
    - libxml2-devel
    - libtidy
    - libmcrypt
    - curl-devel
    - readline-devel
    - libxslt-devel
    - giflib-devel
    - openssl
    - openssl-devel
    - openssh-clients
    - crontabs
    - libselinux-python

- name: common | Selinux off
  selinux: state=disabled