---
- name: php | install php
  yum: name=php state=present enablerepo=remi,remi-php71

- name: php | install php package
  yum: name={{ item }} state=present enablerepo=remi,remi-php71
  with_items: "{{ php_packages }}"

- name: php | copy php.ini configuration
  template: src=php.ini.j2 dest=/etc/php.ini backup=yes
  notify: php-fpm restart

- name: php | copy php-fpm configuration
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf backup=yes
  notify: php-fpm restart

- name: php | start php-fpm
  service: name=php-fpm state=started enabled=yes
