---
- name: mysql | Set ownership on slow query log file
  file:
    path: "{{ mysql_cnf.tunable.log_slow_queries }}"
    state: touch
    owner: mysql
    group: mysql
    mode: 0640

- name: mysql | Copy my.cnf
  template: src=my.cnf.j2 dest=/etc/my.cnf backup=yes
  notify: mysqld restart
  tags: my_cnf

- name: mysql | Running and enabled
  service:
    name=mysqld
    state=started
    enabled=yes
  tags: mysqld
